/**
 * 原型用的 Mock 产品库。每个品类一组。
 *
 * 数据格式与 dimensions 解耦：维度 key 由各品类的 dimensions 决定，
 * 这里只负责填数。新增产品时复制现有结构即可。
 */
import type { CategoryKey, DimensionKey } from "./dimensions";

export type BuyLink = { label: string; url: string };
export type Spec = { label: string; value: string };

/** 每个维度上的原始评分 0..100；key 跟随 dimensions 配置 */
export type ProductScores = Record<DimensionKey, number>;

export type Product = {
  id: string;
  brand: string;
  name: string;
  tagline: string;
  /** 人民币定价 */
  price: number;
  /** 原型阶段用 emoji 占位 */
  image: string;
  /** 卡片配色 (HSL 字符串，不含 hsl()) */
  accent: string;
  scores: ProductScores;
  highlights: string[];
  specs: Spec[];
  pros: string[];
  cons: string[];
  buyLinks: BuyLink[];
};

export const MOCK_PRODUCTS: Record<CategoryKey, Product[]> = {
  laptop: [
    {
      id: "mbp14-m4pro",
      brand: "Apple",
      name: 'MacBook Pro 14" (M4 Pro)',
      tagline: "苹果芯创作旗舰，能效之王",
      price: 16999,
      image: "💻",
      accent: "210 8% 60%",
      scores: { performance: 94, battery: 95, portability: 82, display: 96, build: 97, value: 70 },
      highlights: ["M4 Pro 12核", "Liquid Retina XDR", "22 小时续航"],
      specs: [
        { label: "处理器", value: "Apple M4 Pro 12C" },
        { label: "内存", value: "24GB 统一内存" },
        { label: "存储", value: "1TB SSD" },
        { label: "屏幕", value: '14.2" 3024×1964 mini-LED ProMotion' },
        { label: "重量", value: "1.55 kg" },
        { label: "续航", value: "22 小时" },
      ],
      pros: ["macOS 生态 + 极致能效", "屏幕色准与亮度顶级", "风扇几乎不转"],
      cons: ["接口偏少需转接", "起售价较高", "游戏支持有限"],
      buyLinks: [
        { label: "Apple 官网", url: "https://www.apple.com.cn/macbook-pro/" },
        { label: "京东自营", url: "https://search.jd.com/Search?keyword=MacBook+Pro+M4" },
      ],
    },
    {
      id: "xps14-9450",
      brand: "Dell",
      name: "XPS 14 (Core Ultra 9)",
      tagline: "金属一体机身的全能旗舰",
      price: 14299,
      image: "🖥️",
      accent: "220 14% 50%",
      scores: { performance: 86, battery: 78, portability: 84, display: 92, build: 92, value: 74 },
      highlights: ["OLED 触控屏", "RTX 4050", "CNC 铝合金"],
      specs: [
        { label: "处理器", value: "Intel Core Ultra 9 185H" },
        { label: "显卡", value: "RTX 4050 6GB" },
        { label: "屏幕", value: '14.5" 3.2K OLED 触控' },
        { label: "重量", value: "1.74 kg" },
        { label: "续航", value: "12 小时" },
      ],
      pros: ["OLED 屏幕极致观感", "做工质感顶级", "性能释放充分"],
      cons: ["发热与噪音略明显", "续航中规中矩", "电容触控键值需适应"],
      buyLinks: [{ label: "戴尔官网", url: "https://www.dell.com/zh-cn/shop/xps-14" }],
    },
    {
      id: "thinkpad-x1c-g12",
      brand: "Lenovo",
      name: "ThinkPad X1 Carbon Gen 12",
      tagline: "商务旗舰，键盘党挚爱",
      price: 12999,
      image: "📓",
      accent: "0 0% 20%",
      scores: { performance: 78, battery: 84, portability: 95, display: 84, build: 90, value: 78 },
      highlights: ["1.09 kg 碳纤维", "顶级键盘", "MIL-STD 军规"],
      specs: [
        { label: "处理器", value: "Core Ultra 7 155H" },
        { label: "屏幕", value: '14" 2.8K OLED 120Hz' },
        { label: "重量", value: "1.09 kg" },
        { label: "续航", value: "15 小时" },
      ],
      pros: ["重量与键盘同价位无敌", "商务接口齐全", "稳定性高"],
      cons: ["扬声器一般", "GPU 性能弱", "外观偏保守"],
      buyLinks: [{ label: "联想官网", url: "https://www.lenovo.com.cn/" }],
    },
    {
      id: "yoga-pro14s",
      brand: "Lenovo",
      name: "YOGA Pro 14s (2025)",
      tagline: "国产高刷创作本，预算友好",
      price: 8499,
      image: "✨",
      accent: "270 60% 55%",
      scores: { performance: 82, battery: 76, portability: 80, display: 90, build: 82, value: 92 },
      highlights: ["3K 120Hz OLED", "RTX 4050", "高性价比"],
      specs: [
        { label: "处理器", value: "Core Ultra 9 185H" },
        { label: "显卡", value: "RTX 4050 6GB" },
        { label: "屏幕", value: '14.5" 3K 120Hz' },
        { label: "重量", value: "1.46 kg" },
        { label: "续航", value: "10 小时" },
      ],
      pros: ["万元内最均衡选择", "屏幕素质优秀", "性能释放够用"],
      cons: ["键盘手感普通", "满载噪音偏大"],
      buyLinks: [
        { label: "京东自营", url: "https://search.jd.com/Search?keyword=YOGA+Pro+14s" },
        { label: "天猫官方", url: "https://lenovo.tmall.com/" },
      ],
    },
    {
      id: "rog-zephyrus-g14",
      brand: "ASUS",
      name: "ROG Zephyrus G14 (2025)",
      tagline: "便携游戏本天花板",
      price: 13999,
      image: "🎮",
      accent: "0 70% 50%",
      scores: { performance: 92, battery: 70, portability: 78, display: 88, build: 85, value: 80 },
      highlights: ["RTX 4070", "OLED 165Hz", "1.5 kg 便携"],
      specs: [
        { label: "处理器", value: "Ryzen AI 9 HX 370" },
        { label: "显卡", value: "RTX 4070 8GB" },
        { label: "屏幕", value: '14" 2.8K OLED 120Hz' },
        { label: "重量", value: "1.5 kg" },
        { label: "续航", value: "9 小时" },
      ],
      pros: ["游戏+生产力两开花", "便携性远超同性能段", "屏幕惊艳"],
      cons: ["满载续航偏低", "C 面温度偏高"],
      buyLinks: [{ label: "京东 ROG", url: "https://search.jd.com/Search?keyword=ROG+Zephyrus+G14" }],
    },
    {
      id: "redmibook-pro16",
      brand: "Redmi",
      name: "RedmiBook Pro 16 (2025)",
      tagline: "5K 以内最香生产力",
      price: 4999,
      image: "💼",
      accent: "20 90% 55%",
      scores: { performance: 72, battery: 80, portability: 70, display: 85, build: 76, value: 96 },
      highlights: ["3.2K 165Hz", "5K 内全能", "金属一体"],
      specs: [
        { label: "处理器", value: "Core Ultra 7 155H" },
        { label: "屏幕", value: '16" 3.2K 165Hz' },
        { label: "重量", value: "1.85 kg" },
        { label: "续航", value: "11 小时" },
      ],
      pros: ["性价比拉满", "屏幕大且素质好", "扩展性不错"],
      cons: ["核显机型 GPU 偏弱", "做工一般"],
      buyLinks: [{ label: "小米官网", url: "https://www.mi.com/shop/buy/detail?product_id=20002" }],
    },
    {
      id: "framework-13",
      brand: "Framework",
      name: "Framework Laptop 13",
      tagline: "可维修可升级的极客本",
      price: 9999,
      image: "🛠️",
      accent: "120 50% 40%",
      scores: { performance: 75, battery: 75, portability: 88, display: 78, build: 80, value: 75 },
      highlights: ["模块化接口", "全部件可换", "Linux 友好"],
      specs: [
        { label: "处理器", value: "Core Ultra 7 / Ryzen AI 9" },
        { label: "屏幕", value: '13.5" 2.8K 120Hz' },
        { label: "重量", value: "1.3 kg" },
        { label: "续航", value: "10 小时" },
      ],
      pros: ["接口随心搭配", "维修升级零门槛", "环保理念"],
      cons: ["国内购买不便", "配件需海淘"],
      buyLinks: [{ label: "Framework 官网", url: "https://frame.work/" }],
    },
    {
      id: "asus-zenbook-s14",
      brand: "ASUS",
      name: "Zenbook S 14 (UX5406)",
      tagline: "轻薄与 OLED 并重",
      price: 10999,
      image: "🌌",
      accent: "200 70% 50%",
      scores: { performance: 80, battery: 88, portability: 90, display: 92, build: 86, value: 78 },
      highlights: ["3K OLED", "1.2 kg", "Lunar Lake"],
      specs: [
        { label: "处理器", value: "Core Ultra 7 258V" },
        { label: "屏幕", value: '14" 3K OLED 120Hz' },
        { label: "重量", value: "1.2 kg" },
        { label: "续航", value: "16 小时" },
      ],
      pros: ["轻且续航优秀", "屏幕佳", "能效比高"],
      cons: ["GPU 较弱", "接口偏少"],
      buyLinks: [{ label: "华硕京东", url: "https://search.jd.com/Search?keyword=Zenbook+S+14" }],
    },
    {
      id: "hp-spectre-x360-14",
      brand: "HP",
      name: "Spectre x360 14 (2025)",
      tagline: "二在一转轴旗舰",
      price: 11499,
      image: "🔄",
      accent: "45 60% 50%",
      scores: { performance: 78, battery: 82, portability: 80, display: 90, build: 90, value: 72 },
      highlights: ["360° 翻转", "OLED 触控", "内置手写笔"],
      specs: [
        { label: "处理器", value: "Core Ultra 7 155H" },
        { label: "屏幕", value: '14" 2.8K OLED 触控' },
        { label: "重量", value: "1.4 kg" },
        { label: "续航", value: "13 小时" },
      ],
      pros: ["做工质感强", "手写体验好", "双雷服务"],
      cons: ["重量偏高", "价格偏贵"],
      buyLinks: [{ label: "惠普商城", url: "https://www.hp.com.cn/" }],
    },
    {
      id: "acer-swift-edge-16",
      brand: "Acer",
      name: "Swift Edge 16 (2025)",
      tagline: "大屏轻薄创作本",
      price: 7299,
      image: "🖼️",
      accent: "160 60% 45%",
      scores: { performance: 78, battery: 82, portability: 78, display: 88, build: 80, value: 88 },
      highlights: ["16” OLED", "1.23 kg", "镁金机身"],
      specs: [
        { label: "处理器", value: "Ryzen AI 9 365" },
        { label: "屏幕", value: '16" 3.2K OLED 120Hz' },
        { label: "重量", value: "1.23 kg" },
        { label: "续航", value: "12 小时" },
      ],
      pros: ["同价位最轻的 16 寸", "屏幕顺眼", "性价比高"],
      cons: ["键盘手感一般", "接口一般"],
      buyLinks: [{ label: "Acer 京东", url: "https://search.jd.com/Search?keyword=Swift+Edge+16" }],
    },
    {
      id: "huawei-matebook-x-pro",
      brand: "Huawei",
      name: "MateBook X Pro (2025)",
      tagline: "鸿蒙生态超轻本",
      price: 10999,
      image: "🪶",
      accent: "0 75% 50%",
      scores: { performance: 76, battery: 80, portability: 92, display: 90, build: 88, value: 76 },
      highlights: ["0.97 kg", "3.1K OLED 触控", "鸿蒙互联"],
      specs: [
        { label: "处理器", value: "Core Ultra 9 185H" },
        { label: "屏幕", value: '14.2" 3.1K OLED 触控' },
        { label: "重量", value: "0.98 kg" },
        { label: "续航", value: "13 小时" },
      ],
      pros: ["业内最轻 14”", "跨设备互联便捷", "屏幕优秀"],
      cons: ["接口偏少", "供货偏紧"],
      buyLinks: [{ label: "华为商城", url: "https://www.vmall.com/" }],
    },
  ],

  phone: [
    {
      id: "iphone16-pro",
      brand: "Apple",
      name: "iPhone 16 Pro",
      tagline: "iOS 生态的标杆",
      price: 7999,
      image: "📱",
      accent: "210 8% 60%",
      scores: { performance: 96, camera: 92, battery: 80, display: 94, handfeel: 88, value: 72 },
      highlights: ["A18 Pro", "钛金属", "Apple Intelligence"],
      specs: [
        { label: "SoC", value: "Apple A18 Pro" },
        { label: "屏幕", value: '6.3" LTPO 120Hz' },
        { label: "主摄", value: "48MP + 48MP UW + 12MP 5x" },
        { label: "电池", value: "3582 mAh" },
      ],
      pros: ["生态无敌", "视频拍摄行业第一", "二手保值"],
      cons: ["充电慢", "影像硬件参数偏保守"],
      buyLinks: [{ label: "Apple 官网", url: "https://www.apple.com.cn/shop/buy-iphone/iphone-16-pro" }],
    },
    {
      id: "mate70-pro",
      brand: "Huawei",
      name: "Mate 70 Pro",
      tagline: "鸿蒙旗舰，影像与商务",
      price: 6499,
      image: "📷",
      accent: "0 80% 50%",
      scores: { performance: 86, camera: 96, battery: 88, display: 90, handfeel: 84, value: 80 },
      highlights: ["可变光圈", "卫星通讯", "HarmonyOS NEXT"],
      specs: [
        { label: "SoC", value: "麒麟 9020" },
        { label: "屏幕", value: '6.8" LTPO 120Hz' },
        { label: "主摄", value: "50MP 可变光圈 + 48MP 长焦" },
        { label: "电池", value: "5500 mAh / 100W" },
      ],
      pros: ["影像顶级", "商务功能丰富", "信号优秀"],
      cons: ["应用生态需适应", "游戏性能略弱于骁龙"],
      buyLinks: [{ label: "华为商城", url: "https://www.vmall.com/" }],
    },
    {
      id: "xiaomi15-ultra",
      brand: "Xiaomi",
      name: "Xiaomi 15 Ultra",
      tagline: "徕卡四摄影像旗舰",
      price: 6499,
      image: "🔭",
      accent: "20 90% 55%",
      scores: { performance: 95, camera: 95, battery: 86, display: 92, handfeel: 80, value: 86 },
      highlights: ["徕卡四摄", "骁龙 8 Elite", "5410 mAh"],
      specs: [
        { label: "SoC", value: "骁龙 8 Elite" },
        { label: "屏幕", value: '6.73" 2K LTPO' },
        { label: "主摄", value: "50MP + 50MP UW + 200MP 长焦" },
        { label: "电池", value: "5410 mAh / 90W" },
      ],
      pros: ["影像硬件拉满", "性能顶级", "充电快"],
      cons: ["机身较重", "MIUI 广告需手动关"],
      buyLinks: [{ label: "小米商城", url: "https://www.mi.com/" }],
    },
    {
      id: "oneplus13",
      brand: "OnePlus",
      name: "OnePlus 13",
      tagline: "性能+续航均衡王",
      price: 4499,
      image: "⚡",
      accent: "0 70% 50%",
      scores: { performance: 94, camera: 84, battery: 92, display: 92, handfeel: 86, value: 92 },
      highlights: ["6000 mAh", "100W 快充", "骁龙 8 Elite"],
      specs: [
        { label: "SoC", value: "骁龙 8 Elite" },
        { label: "屏幕", value: '6.82" 2K LTPO' },
        { label: "电池", value: "6000 mAh / 100W" },
      ],
      pros: ["续航无忧", "性能旗舰", "屏幕优秀"],
      cons: ["影像略弱于同价超大杯"],
      buyLinks: [{ label: "一加官网", url: "https://www.oneplus.com/cn" }],
    },
    {
      id: "redmi-k80-pro",
      brand: "Redmi",
      name: "Redmi K80 Pro",
      tagline: "3K 价位性能怪兽",
      price: 3299,
      image: "🚀",
      accent: "220 90% 55%",
      scores: { performance: 92, camera: 78, battery: 88, display: 88, handfeel: 82, value: 96 },
      highlights: ["骁龙 8 Gen 3", "120W 快充", "性价比之王"],
      specs: [
        { label: "SoC", value: "骁龙 8 Gen 3" },
        { label: "屏幕", value: '6.67" 2K 120Hz' },
        { label: "电池", value: "6000 mAh / 120W" },
      ],
      pros: ["性能价格比无敌", "充电极快", "屏幕规格好"],
      cons: ["影像中规中矩", "机身偏重"],
      buyLinks: [{ label: "小米商城", url: "https://www.mi.com/" }],
    },
    {
      id: "vivo-x200-pro",
      brand: "vivo",
      name: "vivo X200 Pro",
      tagline: "蔡司影像 + 天玑 9400",
      price: 5999,
      image: "🎞️",
      accent: "210 80% 55%",
      scores: { performance: 90, camera: 94, battery: 90, display: 92, handfeel: 86, value: 84 },
      highlights: ["蔡司 APO 长焦", "6000 mAh", "天玑 9400"],
      specs: [
        { label: "SoC", value: "天玑 9400" },
        { label: "屏幕", value: '6.78" 2K LTPO' },
        { label: "电池", value: "6000 mAh / 90W" },
      ],
      pros: ["长焦人像极佳", "续航优秀", "做工精致"],
      cons: ["系统略重", "二手保值率一般"],
      buyLinks: [{ label: "vivo 商城", url: "https://shop.vivo.com.cn/" }],
    },
  ],

  headphone: [
    {
      id: "airpods-pro2",
      brand: "Apple",
      name: "AirPods Pro 2 (USB-C)",
      tagline: "Apple 生态的标准答案",
      price: 1899,
      image: "🎧",
      accent: "210 8% 60%",
      scores: { anc: 90, sound: 84, comfort: 92, battery: 78, ecosystem: 98, value: 78 },
      highlights: ["自适应音频", "无损支持(Vision)", "听力测试"],
      specs: [
        { label: "续航", value: "6h + 30h" },
        { label: "降噪", value: "主动降噪 / 通透" },
      ],
      pros: ["生态切换无感", "通话麦克风顶级", "佩戴稳"],
      cons: ["音质中规中矩", "维修成本高"],
      buyLinks: [{ label: "Apple 官网", url: "https://www.apple.com.cn/shop/buy-airpods/airpods-pro" }],
    },
    {
      id: "sony-wf1000xm5",
      brand: "Sony",
      name: "Sony WF-1000XM5",
      tagline: "降噪与音质双修",
      price: 1899,
      image: "🎵",
      accent: "0 0% 20%",
      scores: { anc: 96, sound: 92, comfort: 86, battery: 80, ecosystem: 78, value: 82 },
      highlights: ["业界顶级降噪", "LDAC", "DSEE Extreme"],
      specs: [
        { label: "续航", value: "8h + 24h" },
        { label: "编解码", value: "LDAC / AAC / SBC" },
      ],
      pros: ["降噪天花板", "音质细腻", "APP 自定义丰富"],
      cons: ["佩戴需选耳塞", "通话一般"],
      buyLinks: [{ label: "索尼中国", url: "https://www.sonystyle.com.cn/" }],
    },
    {
      id: "bose-qcue",
      brand: "Bose",
      name: "Bose QC Ultra Earbuds",
      tagline: "通勤降噪利器",
      price: 2299,
      image: "🛡️",
      accent: "0 70% 50%",
      scores: { anc: 94, sound: 88, comfort: 88, battery: 76, ecosystem: 74, value: 72 },
      highlights: ["沉浸式音频", "卓越降噪", "鲨鱼鳍贴合"],
      specs: [{ label: "续航", value: "6h + 24h" }],
      pros: ["降噪贴近 XM5", "佩戴稳", "调音耐听"],
      cons: ["价格偏高", "无 LDAC"],
      buyLinks: [{ label: "Bose 中国", url: "https://www.bose.cn/" }],
    },
    {
      id: "huawei-freebuds-pro4",
      brand: "Huawei",
      name: "FreeBuds Pro 4",
      tagline: "鸿蒙原生 + 高音质",
      price: 1499,
      image: "🪶",
      accent: "0 80% 50%",
      scores: { anc: 90, sound: 92, comfort: 88, battery: 80, ecosystem: 86, value: 90 },
      highlights: ["L2HC 无损", "三麦克风", "空间音频"],
      specs: [{ label: "续航", value: "7h + 33h" }],
      pros: ["音质惊艳", "佩戴舒适", "鸿蒙设备无感切换"],
      cons: ["iOS 端功能受限"],
      buyLinks: [{ label: "华为商城", url: "https://www.vmall.com/" }],
    },
    {
      id: "redmi-buds6-pro",
      brand: "Redmi",
      name: "Redmi Buds 6 Pro",
      tagline: "500 价位最香",
      price: 499,
      image: "💎",
      accent: "20 90% 55%",
      scores: { anc: 82, sound: 80, comfort: 84, battery: 78, ecosystem: 78, value: 96 },
      highlights: ["三单元", "LDAC 支持", "百元降噪"],
      specs: [{ label: "续航", value: "7h + 30h" }],
      pros: ["性价比超高", "三频均衡", "降噪够用"],
      cons: ["生态比不上一线"],
      buyLinks: [{ label: "小米商城", url: "https://www.mi.com/" }],
    },
    {
      id: "moondrop-cosmos2",
      brand: "Moondrop",
      name: "Moondrop Cosmo 2",
      tagline: "HIFI 玩家口粮",
      price: 999,
      image: "🌌",
      accent: "270 60% 55%",
      scores: { anc: 70, sound: 96, comfort: 82, battery: 72, ecosystem: 60, value: 86 },
      highlights: ["平面振膜", "Hi-Res 认证", "调音可调"],
      specs: [{ label: "续航", value: "6h + 24h" }],
      pros: ["音质惊喜", "解析力强", "HIFI 入门"],
      cons: ["降噪一般", "生态弱"],
      buyLinks: [{ label: "水月雨天猫", url: "https://moondrop.tmall.com/" }],
    },
  ],
};

/** 按品类 key 获取产品列表 */
export function getProducts(catKey: CategoryKey): Product[] {
  return MOCK_PRODUCTS[catKey] ?? [];
}
